products = [
    {
        "title": "Printer",
        "category": "Electronics",
        "description": "Super awesome printer",
        "price": 150.00,
        "quantity": 5,
        "image_title": "printer.png",
        "is_top_deal": "false",
    },
    {
        "title": "Paint Brushes",
        "category": "Arts and Crafts",
        "description": "Paint your life away",
        "price": 25.00,
        "quantity": 15,
        "image_title": "paint-brushes.png",
        "is_top_deal": "true",
    },
    {
        "title": "Printer Paper",
        "category": "Office Supplies",
        "description": "Paper for your printer",
        "price": 30.00,
        "quantity": 500,
        "image_title": "printer-paper.jpg",
        "is_top_deal": "true",
    },
    {
        "title": "Pens",
        "category": "Office Supplies",
        "description": "Write your name, a book, or anything in between",
        "price": 9.99,
        "quantity": 35,
        "image_title": "pens.png",
        "is_top_deal": "true",
    },
    {
        "title": "Midi Keyboard",
        "category": "Musical Instruments",
        "description": "Play to your hearts content",
        "price": 400.00,
        "quantity": 2,
        "image_title": "midi-keyboard.png",
        "is_top_deal": "true",
    },
    {
        "title": "TV",
        "category": "Electronics",
        "description": "Watch all the movies",
        "price": 150.00,
        "quantity": 7,
        "image_title": "tv.png",
        "is_top_deal": "false",
    },
    {
        "title": "Leather Jacket",
        "category": "Clothing",
        "description": "Stylish jacket",
        "price": 75.00,
        "quantity": 12,
        "image_title": "jacket.png",
        "is_top_deal": "true",
    },
    {
        "title": "Pillow",
        "category": "Home Goods",
        "description": "Most comfortable pillow ever",
        "price": 25.00,
        "quantity": 1000,
        "image_title": "comfy-pillow.png",
        "is_top_deal": "false",
    },
    {
        "title": "Gold Neckless",
        "category": "Accessories",
        "description": "Impress anyone with this awesome gift",
        "price": 150.00,
        "quantity": 2,
        "image_title": "neckless.png",
        "is_top_deal": "false",
    },
]
