"""default --> server_default

Revision ID: 154a3289dc14
Revises: 2d68c4ef0936
Create Date: 2022-09-28 15:58:34.970681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154a3289dc14'
down_revision = '2d68c4ef0936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
