"""Added large binary type column for images in products table

Revision ID: 1817c81cc12c
Revises: 81ada111f899
Create Date: 2022-10-12 15:48:16.849740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1817c81cc12c'
down_revision = '81ada111f899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
