"""Revert

Revision ID: 1caa7b06b159
Revises: 4a98488478ff
Create Date: 2022-10-15 12:16:37.166607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caa7b06b159'
down_revision = '4a98488478ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_image_paths_product_id_fkey', 'product_image_paths', type_='foreignkey')
    op.drop_column('product_image_paths', 'product_id')
    op.add_column('products', sa.Column('image_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'product_image_paths', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    op.add_column('product_image_paths', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_image_paths_product_id_fkey', 'product_image_paths', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
