"""text(0)

Revision ID: 245dc7059ac0
Revises: 154a3289dc14
Create Date: 2022-09-28 16:07:42.484463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245dc7059ac0'
down_revision = '154a3289dc14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
