"""Changed default to server_default in created_at row

Revision ID: 2d68c4ef0936
Revises: 6588ed0b7e78
Create Date: 2022-09-28 15:51:34.277968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d68c4ef0936'
down_revision = '6588ed0b7e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
