"""Established relationship between ProductImagePath model and Product model

Revision ID: 32ec4cf68ac8
Revises: 51de08ce050b
Create Date: 2022-10-14 13:37:54.867019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ec4cf68ac8'
down_revision = '51de08ce050b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
