"""Added boolean value stating whether a product is a top deal

Revision ID: 3935db4203cc
Revises: e079289287c0
Create Date: 2022-10-17 14:45:08.261571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3935db4203cc'
down_revision = 'e079289287c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('top_deal', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'top_deal')
    # ### end Alembic commands ###
