"""latest

Revision ID: 4a98488478ff
Revises: a5366fbc5da2
Create Date: 2022-10-15 11:56:45.859318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a98488478ff'
down_revision = 'a5366fbc5da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image_paths', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('product_image_paths', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'product_image_paths', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_image_path_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'image_path_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_image_path_id_fkey', 'products', 'product_image_paths', ['image_path_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_image_paths', type_='foreignkey')
    op.drop_column('product_image_paths', 'created_at')
    op.drop_column('product_image_paths', 'product_id')
    # ### end Alembic commands ###
