"""typo

Revision ID: 51de08ce050b
Revises: e65af7bd1cd6
Create Date: 2022-10-13 17:15:56.695211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51de08ce050b'
down_revision = 'e65af7bd1cd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
