"""Column name change to concise identifier

Revision ID: 51fbbabd3663
Revises: 7f17ad80e76e
Create Date: 2022-10-27 10:56:45.553347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fbbabd3663'
down_revision = '7f17ad80e76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_quantity', sa.Integer(), nullable=False))
    op.drop_column('cart_items', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cart_items', 'product_quantity')
    # ### end Alembic commands ###
