"""Removed the rating column for the Product model

Revision ID: 70576a232360
Revises: 1cfe4b7b97aa
Create Date: 2022-10-26 14:47:43.683286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70576a232360'
down_revision = '1cfe4b7b97aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
