"""Added quantity column to CartItem model in order to track how many of a given product a user wants to buy

Revision ID: 7f17ad80e76e
Revises: 70576a232360
Create Date: 2022-10-27 09:49:58.675566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f17ad80e76e'
down_revision = '70576a232360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'quantity')
    # ### end Alembic commands ###
