"""corrected default value for rating column from string to integer

Revision ID: 8ad3e58b11bf
Revises: dbe4cffb2ada
Create Date: 2022-09-28 15:44:03.994720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad3e58b11bf'
down_revision = 'dbe4cffb2ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
