"""Added a category column into the products model

Revision ID: 8f358b5ec3c3
Revises: 8db34a276297
Create Date: 2022-09-29 10:14:02.645818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f358b5ec3c3'
down_revision = '8db34a276297'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
