"""Added category, price, and quantity columns for products table

Revision ID: 92acabe5084a
Revises: c2a904a30226
Create Date: 2022-09-30 10:50:02.464537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92acabe5084a'
down_revision = 'c2a904a30226'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
