"""latest

Revision ID: a5366fbc5da2
Revises: 8fc7faa03ba4
Create Date: 2022-10-14 15:54:18.042117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5366fbc5da2'
down_revision = '8fc7faa03ba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
