"""Added column to carts model displaying how many items are in the cart. Additionally, established relationship between the cart_items model and the products model

Revision ID: cd3e357cc46c
Revises: 8f358b5ec3c3
Create Date: 2022-09-29 17:29:18.662595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3e357cc46c'
down_revision = '8f358b5ec3c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('carts', sa.Column('cart_quantity', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'cart_quantity')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'product_id')
    # ### end Alembic commands ###
