"""Relationship between products and product_image_paths correction

Revision ID: ddbebe056175
Revises: 32ec4cf68ac8
Create Date: 2022-10-14 14:25:39.328659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbebe056175'
down_revision = '32ec4cf68ac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
