"""Changed Column name "top_deal" to "is_top_deal"

Revision ID: e06c110d274b
Revises: 3935db4203cc
Create Date: 2022-10-17 14:50:07.191663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06c110d274b'
down_revision = '3935db4203cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_top_deal', sa.Boolean(), server_default='False', nullable=True))
    op.drop_column('products', 'top_deal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('top_deal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('products', 'is_top_deal')
    # ### end Alembic commands ###
