"""newest

Revision ID: e079289287c0
Revises: 1caa7b06b159
Create Date: 2022-10-15 12:24:23.690094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e079289287c0'
down_revision = '1caa7b06b159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image_paths', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_image_paths', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_image_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_image_id_fkey', 'products', 'product_image_paths', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_image_paths', type_='foreignkey')
    op.drop_column('product_image_paths', 'product_id')
    # ### end Alembic commands ###
