"""Added new cart creation on new user creation

Revision ID: e11e3e2552ba
Revises: 92acabe5084a
Create Date: 2022-09-30 13:58:51.597295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11e3e2552ba'
down_revision = '92acabe5084a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'created_at')
    # ### end Alembic commands ###
