"""Changed image column from a byte array storing an images binary to a string containing a path to where the image is stored on the machines file system

Revision ID: e9f8e9f2b8aa
Revises: 1817c81cc12c
Create Date: 2022-10-13 11:30:48.970734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9f8e9f2b8aa'
down_revision = '1817c81cc12c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.String(), nullable=False))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
